### ISSUE TITLE
Consider requiring halfops instead of ops for RELAYMSG

### ISSUE THREAD

**Issue by Mikaela** [ergochat/ergo#1519]
According to @slingamn halfops allow kicking, but not banning (and typing this I assume not setting other modes). I think this is limited usability and I wouldn't use halfops much, but I think it could be useful for RELAYMSG bots so in case there is a problem that lets users to send commands as the bot or it's password leaks or anything, it cannot be abused that much.

Thus I think it's worth considering to require halfops instead of ops for using RELAYMSG as it may be more comfortable for users to give a relaybot halfop than actual op if they aren't server operators and cannot give opers.

**Comment by slingamn** [comment]
This is definitely worth considering. I'm waiting to hear more about how RELAYMSG is or isn't disruptive to legacy clients.

**Comment by Mikaela** [comment]
Actually would there be a point in changing `available-to-chanops: true` to `available-to-mode: ` and then take argument `founder/protected/op/halfop/voice` or simply `+q/+a/+o/+h/+v` ?

**Comment by Mikaela** [comment]
Another thing halfops (with amode) can do is getting through +i ([according to the manual](https://github.com/ergochat/ergo/blob/master/docs/MANUAL.md#how-do-i-make-a-private-channel)) so I have an actual use for halfops and no longer support this issue.
