### ISSUE TITLE
ergo.chat/persistence

### ISSUE THREAD

**Issue by DanielOaks** [ergochat/ergo#1551]
Tracking issue for a possible capability that inherits stuff from this comment and the next few: https://github.com/oragono/oragono/issues/1527#issuecomment-782901880

The basic part of this capability is just enabling persistence tracking, e.g. which clients are active and which ones aren't right now. Take inspiration from ZNC's `clientaway` module linked there, the sorta `BACKGROUND` / `FOREGROUND` stuff that the Palaver spec mentions, that kind of thing.

I imagine that maybe the value of this cap could be a list of functionalities, separated by commas, if there are more interfaces directly tied to this persistence that need to be tracked. But even mentioning that makes this feel like **`ACC` oh no big bloated spec** so that's just an idea that I probably hate.

Comment from @kylef on this _sort_ of a thing and how a client could possibly use the info that 'you are persistent':

> [...] it would be nice to understand that our "session" outlives our connection so that it may be safe from a client point of view to make more than 1 IRC connection in background, for out of main process uses (replying to message from notification, watch, another application via a "share" extension). That and also knowing that connecting does not have side-effects like clearing buffers (ZNC this is possible based on configuration), changing away/unaway status, changing presence.

It should be noted, this differs from the `BOUNCER` spec because the `BOUNCER` spec is aimed towards managing a traditional IRC bouncer that can have multiple networks, managing those networks, etc, whereas this is aimed at exposing persistence stuff in the context of this specific thing that you're connected to, and doesn't touch the consideration that any other networks exist at all.

**Comment by DanielOaks** [comment]
re this, it probably makes sense to e.g. note down what's on things like textual's "ZNC-specific features" configuration screen, because those are the kind of things that would likely be used in this or where we could use this cap to note the 'configuration of the server' to the client so those checkboxes become redundant and are auto-set to the correct values.

**Comment by slingamn** [comment]
I was thinking, this can be an 005 instead of a CAP, but the idea of making a "silent" connection to the ircd (that doesn't have side effects) militates in favor of it being a CAP (i.e., you request the CAP and you get a silent connection).

AWAY is tricky because #1531 would entail that making a new connection renders you "back".

Apart from that, the CAP value (or the 005 value, if we go that route) can just convey whether permanence is disabled, opt-in, opt-out, or mandatory (as in our current config option), and we can add a command that gets and sets the setting (duplicating our current `NS SET ALWAYS-ON`).

**Comment by DanielOaks** [comment]
Note to self, we'll probably have the default case which is "client doesn't support pushing persistence info to server" (desktop clients, etc). In this case, the server will just make judgement calls as to whether clients are active or not, also helped by `AWAY` and the way we tackle it in #1531. I imagine that the language in the spec here can be pretty loose and allow the (server or server equivalent) to handle it in however they want, which'd open up ZNC's clientaway stuff to be the basis for this too.

And the actually-used case which is e.g. mobile client sending `FOREGROUND` when establishing the connection, and then keeping the server updated with FG/BG calls.

**Comment by DanielOaks** [comment]
@kylef mentions that maybe instead of the terms foreground/background, something like 'idle' which the client can determine would make sense as more general (what's the opposite of idle, unidle, no_more_idle?)

**Comment by slingamn** [comment]
[pounce](https://git.causal.agency/pounce/about/pounce.1) defines a vendor cap `causal.agency/passive` for making a "silent" connection.

**Comment by slingamn** [comment]
The current direction we're going in is #2044 (`draft/pre-away`)
