### ISSUE TITLE
SNO for disconnecting session by an always-on or multiclient Account 

### ISSUE THREAD

**Issue by mogad0n** [ergochat/ergo#1644]
New sessions produce a CONNECT sno but a closed session that does not cause a QUIT (because of multiclient or always-on) does not produce any sno.
Would be useful for ircops or bots to have some sno lines similar disconnecting session log-line.

**Comment by mogad0n** [comment]
How far am I from a solution? [PR comparision](https://git.com.de/mogad0n/ergo/compare/master...feature/sess_disconn_sno)
I understand that `irc/sno/utils_test.go` and maybe some other stuff needs to be updated but that is if this is even viable.

**Comment by slingamn** [comment]
This seems fine, want to PR it?

**Comment by slingamn** [comment]
Fixed by  #1728
