### ISSUE TITLE
handle SMTP 451 (greylisting)

### ISSUE THREAD

**Issue by slingamn** [ergochat/ergo#1659]
This came up twice today with irc.ergo.chat: registration emails were rejected by greylisting (SMTP code 451).

In theory Ergo could queue and retry these verification emails; the impact on UX is unclear. (What do we report to the user? What do other email-based account verification systems do here?)

**Comment by tacerus** [comment]
Hi,

In theory the sender of an email receives an error message back via mailer-daemon, in this case the email sender obviously is an integrated application - I am unaware of any specifications for this usecase, however think that retrying as per the sending SMTP servers configuration and catching the exemption with a message that indicates the delay to the user would be sufficient. As a bonus feature, it would be good to allow the user to try a different email address, if they prefer not to wait.

For reference - albeit, from my understanding, mostly targeted at the email receivers implementation of greylisting: https://datatracker.ietf.org/doc/html/rfc6647

In addition to that, I would highly suggest recommending common email server practices to prevent emails from being greylisted and/or marked as spam in the first place.
The following issues were detected by rspamd (along with the strike points):

```
From | admin@ergo.chat
-- | --
MX_MISSING (3.5) []
SEM_URIBL_FRESH15 (3) [ergo.chat:dkim]
BAD_REP_POLICIES (2)
MX_INVALID (0.5) []
DWL_DNSWL_FAIL (0) [ergo.chat:server fail]
```
resulting in
`GREYLIST (0) [greylisted, Thu, 27 May 2021 05:06:36 GMT, new record]`

The blacklist ones may originate from the domain and/or IP address not having gained reputation yet, however the missing MX, missing DMARC (dmarc=none) are easy implementations which would help your originating emails get passed through more often a lot. Just as proof it is not an issue with my custom mail/spam setup: I just attempted with a @gmail.com address, which failed too.

**Comment by slingamn** [comment]
Did it hard-fail on gmail, or just get sent to spam? I tested this successfully earlier.

**Comment by tacerus** [comment]
Hard fail. You should check the received mails headers in GMail - it has a nice output showing which checks passed and which failed.

**Comment by tacerus** [comment]
That does not mean much. Email delivery can be wary if requirements are not met. Especially big providers like Google have their own ways of filtering their routing.

**Comment by slingamn** [comment]
I don't really want to implement automatic retries. I think I'll just go in the direction of reporting more information about the email delivery error to the end user; if the end user sees that their verification email was rejected by greylisting, they can retry registration in 30 minutes or whatever.

**Comment by tacerus** [comment]
Sounds reasonable.

For your own network, it'd still be good to configure the mailserver to prevent it from happening too often.
