### ISSUE TITLE
Ergo is IRCd and service, why not split it into two services (software)?

### ISSUE THREAD

**Issue by avelino** [ergochat/ergo#1673]
I like the idea of having everything contained in the same software, but thinking about scaling software we will have to go up any instances of ergo (IRCd and service) regardless of where the bottleneck is 

- DDoS attack needs to scale IRCd, not service 
- Many users using *service need to scale service

**Comment by slingamn** [comment]
Thanks for the suggestion!

Unfortunately or fortunately, "vertical integration" of ircd and services in Ergo is essential to our design --- it's what makes strict nickname enforcement, multiclient, and always-on possible.

Have you seen #1532? That's our current design for horizontal scalability: the "services node" (such as it is) will remain part of the master node, and we don't expect that this will be a significant barrier in terms of our scalability goals.

**Comment by avelino** [comment]
I was not aware of this issue 1532, it explains how it is possible to scale horizontally the ergo
