### ISSUE TITLE
restrict # in nicknames and relaymsg

### ISSUE THREAD

**Issue by slingamn** [ergochat/ergo#1679]
1. `#` should be added to `disfavoredNameCharacters`
2. `#` should be disallowed as the relaymsg separator

**Comment by slingamn** [comment]
Adding `#` to `disfavoredNameCharacters` is unproblematic; after we do that, the list of disfavored characters will be `<>'";#`. Any objections to disallowing all of these characters as the relaymsg separator?

**Comment by Mikaela** [comment]
I understand # to break channels, but what is the reasoning to the other characters? Is it `;` or `:` that is forbidden? Wasn't `@` also problematic?

**Comment by slingamn** [comment]
This is pretty confusing. The `protocolBreakingNameCharacters` (which have always been banned) are ` ,*?.!@:`. The `disfavoredNameCharacters`, listed above, are characters that were not originally banned, but which we subsequently realized were problematic, so they're banned in new nicknames and account names but not in preexisting registered nicknames.
