### ISSUE TITLE
ACCEPT command and auto-accept upon PM

### ISSUE THREAD

**Issue by Mikaela** [ergochat/ergo#1688]
> /accept allows nickname to PM regardless of +Rg and is done automatically by Chary upon messaging someone who isn't allowed to reply to you otherwise

Could resolve https://github.com/ergochat/ergo/issues/1687

See also Chary/Solanum /quote help accept

**Comment by Mikaela** [comment]
Spec: https://github.com/solanum-ircd/solanum/blob/main/doc/features/modeg.txt

It's difficult to read on mobile but in case of +Rg, only registered users trigger the notification.

**Comment by slingamn** [comment]
I like the idea of doing this for v2.10:

1. Add an ACCEPT command
2. Sending a DM has the same effect as an ACCEPT, implicitly

@progval this would eliminate the need for #1687, right?

**Comment by progval** [comment]
yes
