### ISSUE TITLE
Add --daemonize option

### ISSUE THREAD

**Issue by tacerus** [ergochat/ergo#1690]
Hi,

one can set the log type to `stderr` and try the `--quiet` option as described [here](https://github.com/ergochat/ergo/issues/276#issuecomment-399810018), which makes ergo not print any output to stderr, however it will stick at an empty prompt and not daemonize to the background.

This causes issues if the user wants to run ergo as a service on non-systemd based systems (for example Slackware or NetBSD), as init based systems rely on the application to daemonize itself. 

As a hack one can use tools such as `nohup` or `daemonizer`, however this is not a clean solution, and it would be nice of ergo supported legacy init systems out of the box.

Thanks!

**Comment by slingamn** [comment]
As I understand it, each such platform has a recommended solution for this, e.g. [daemon(8)](https://www.freebsd.org/cgi/man.cgi?query=daemon&sektion=8) on FreeBSD, or [start-stop-daemon(8)](https://man7.org/linux/man-pages/man8/start-stop-daemon.8.html) on non-systemd Linuxes?

I don't really see the advantages of supporting this within Ergo.

**Comment by tacerus** [comment]
I.e. Slackware do explicitly ask for the program to support a `--daemonize` option. The alternative is to use `nohup`, but this is seen as a hack.

**Comment by slingamn** [comment]
Do you have a reference for the Slackware guidelines?

I don't really want to do this; it seems like debt and it will create portability issues that didn't exist before (compare the workaround we do for [signals on plan9](https://github.com/ergochat/ergo/blob/e59d599eed815105dc5665e252607f8f37c9b97c/irc/signals_plan9.go)).

**Comment by tacerus** [comment]
I do not have a link, however talking to Slackware people this response sums the universal idea up quite well:

> 08:41 \<skyroveRR\>  slackware by itself doesn't have an distro-specific program to daemonise. The rc.X scripts basically invoke some option or the other to cause the program to daemonise. So all you have to suggest to the author of ergochat is to write some extra code to daemonise it, and that option can then be used inside an rc.ergochat or whatever init script. The reason being, almost all of the init scripts in
08:41 \<skyroveRR\> slackware don't run a process in foreground. Foregrounding a process is very runit/systemd-specific because the init daemon in that regard can keep tab of the process and notify the user and/or reinitialise the program if it gets killed abnormally. Slackware's init on the other hand, doesn't have the ability to "track" a daemon.

**Comment by slingamn** [comment]
I recommend `start-stop-daemon(8)` for Linuxes without systemd; I would accept a PR that added an example init script to `distrib/`.

**Comment by tacerus** [comment]
OK, `start-stop-daemon` worked fine, however needed manual install. I found a similar program called `daemon` to be quickly installable via slackpkg and made a script for it. I think I included all features that `systemctl` provides in regards to controlling ergo (start, stop, restart, reload, status), but let me know if I missed something.

**Comment by slingamn** [comment]
Resolved by #1691.
