### ISSUE TITLE
SNOTICES are missing device IDs

### ISSUE THREAD

**Issue by Mikaela** [ergochat/ergo#1711]
When I connect to multi-client, my existing connections see:

```
2021-177 01:27:51 EEST -- etro.mikaela.info: -CONNECT- Client connected [Mikaela] [u:~u] [h:REDACTED] [ip:REDACTED] [r:Mikaela <REDACTED@mikaela.info>]
2021-177 01:27:51 EEST -- etro.mikaela.info: -ACCOUNT- Client [Mikaela!~u@mikaela.info] logged into account [Mikaela]
```

This doesn't tell me much and I wish to see the client identifier so I would know whether this is my phone or if my HexChat is having connection issues or if I am on phone, is it possible my WeeChat is having trouble connecting.

It seems like the SNOTICES are only given to operators and I was wondering if client identifiers not being exposed might be a privacy feature, but considering I can `/ns clients list anotherUser`, I guess this may just be an oversight.

Loosely related: https://github.com/ergochat/ergo/issues/1706

Versions: ergo-2.7.0 (2 instances), ergo-2.7.0-rc1 36703580fc460ec2 (1 instance)

**Comment by slingamn** [comment]
You're right that there's no privacy reason not to do this.

However, this change would likely break [existing uses of HOPM](https://github.com/ergochat/ergo/blob/master/docs/MANUAL.md#hybrid-open-proxy-monitor-hopm), so it needs some consideration.

**Comment by slingamn** [comment]
From discussion I'm going to wontfix this, because of the compatibility concern.

If you're debugging your own devices you'll likely be able to tell them apart by the IP address ranges.

**Comment by Mikaela** [comment]
> If you're debugging your own devices you'll likely be able to tell them apart by the IP address ranges.

They will same the same IP range if they are running in the same network like a desktop or two + mobile client(s)
