### ISSUE TITLE
Who query for opers returns all nicks

### ISSUE THREAD

**Issue by kylef** [ergochat/ergo#1730]
When requesting the who list, using the `o` (oper only) parameter from rfc1459 results in returning all nicks.

```
C: WHO * o
```

> If the "o" parameter is passed only operators are returned according to the name mask supplied [[rfc1459](https://datatracker.ietf.org/doc/html/rfc1459#section-4.5.1)]

**Comment by slingamn** [comment]
https://github.com/ergochat/ergo/blob/c53df2dc88f371232d2775fc52f3fb2eb95a1388/irc/handlers.go#L3283-L3288

We might be trying to deprecate this?

**Comment by slingamn** [comment]
Consider returning an empty list for this.

**Comment by slingamn** [comment]
@progval thoughts on returning an empty list here?

**Comment by progval** [comment]
Why?

**Comment by slingamn** [comment]
I'm sympathetic to the idea in @DanielOaks's comment that this feature is cruft and should be deprecated. Independently of this, we're trying to move away from a binary distinction between operators and non-operators, instead relying on the capability system (#1176 for some context).

On the other hand, we do still return binary operator/non-operator flags in WHO, WHOIS, and USERHOST.

**Comment by progval** [comment]
Hmm I don't know. We could use the WHOX token to advertize support for it https://github.com/ircv3/ircv3-specifications/issues/81#issuecomment-787171315

**Comment by emersion** [comment]
The "o" flag is quite useful to clients, it's the only standard way to list server operators. The binary flag in the WHO replies is used by gamja to add a "server operator" label when talking to a server op.

**Comment by emersion** [comment]
gamja doesn't, but may send `WHO * o` in the future to provide a UI to display server operators. This is useful to ask for help on a network.

`WHO *` and then filtering for operators will flood the client with a list of all users.

**Comment by slingamn** [comment]
>Maybe consider dropping the flag like Libera Chat does then?

Makes sense. We have a `stealth` key that can be set in the operator configuration and hides operator status from WHO, USERHOST, and WHOIS; the recommended default value right now is `false`, but maybe it should be `true`.

**Comment by slingamn** [comment]
Possibly relevant, on a traditional ircd the `*` flag has a TOCTOU race when used for this purpose; if you don't share a channel with the user, you won't see their QUIT line, and then someone else might claim the nickname.

**Comment by slingamn** [comment]
Follow-up, `o` is officially deprecated! https://github.com/ircdocs/modern-irc/pull/138
