### ISSUE TITLE
Response to LIST doesn't begin with RPL_LISTSTART

### ISSUE THREAD

**Issue by akinwale** [ergochat/ergo#1734]
The first reply to `LIST` on irc.ergo.chat is `RPL_LIST` (322), along with the subsequent replies until `RPL_LISTEND` (323) which indicates the end of the list.

It would be useful to always have `RPL_LISTSTART` (321) as the initial reply to a `LIST` request.

**Comment by slingamn** [comment]
Thanks for the report. There's some previous discussion at #1335. I decided against changing this previously but I might reconsider --- if you have thoughts, feel free to comment there so that all the discussion is in one place.
