### ISSUE TITLE
Rename draft/register to draft/account-registration

### ISSUE THREAD

**Issue by delthas** [ergochat/ergo#1740]
https://github.com/ircv3/ircv3-specifications/pull/435#issuecomment-827963560

**Comment by DanielOaks** [comment]
To be clear, the cap name was rolled back until a change was made, and the actual latest change that rolled the cap name to `draft/account-registration` was [this one](https://github.com/ProgVal/ircv3-specifications/pull/1/files). We should only rename the cap once we support parsing the new `<accountname>` parameter of the `REGISTER` command -- it's not a 1-for-1 swap from the old cap name to the new one.

**Comment by slingamn** [comment]
Sorry, I somehow missed all of this discussion. Let's get this done for 2.8.
