### ISSUE TITLE
Issue on Docker Swarm, all client connect detected from single IP

### ISSUE THREAD

**Issue by kingter-sutjiadi** [ergochat/ergo#1780]
Hi, i'm having issue when deploying on Dockerswarm

the issue is all client that connected on the ergochat node is detected from 1 IP the ip was the Ingress network node

this force us to edit max-concurrent-connections value under the ip-limits.

does anyone have other workaround with the issue?

Thank you inb4

**Comment by DanielOaks** [comment]
Hi @kingter-sutjiadi! We support the [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) described by HAProxy to set the ingress IPs correctly.

Hopefully there should be a way to enable using this protocol for ingress connections to Ergo. With that, [this section of our Manual](https://github.com/ergochat/ergo/blob/master/docs/MANUAL.md#reverse-proxies) describes how to enable our PROXY support on Ergo.

Please let us know if there's any trouble with these. If you can't find where to enable that protocol, the please feel free to drop onto our IRC channel to chat more about your setup and point you in the right direction! (hopefully searching for `PROXY protocol` plus the name of the software you're using should return some good results).

**Comment by kingter-sutjiadi** [comment]
Hi @DanielOaks , thanks for fast response, i'll try and take a look about it

**Comment by kingter-sutjiadi** [comment]
Hi @DanielOaks sry for late response, we decided to move to a VM instead of dockerize things, and seems it's working well, so our systems just go from HA proxy -> VM now, Instead of HA Proxy -> dockerSwarm ingress LB -> docker container,

thank you for the response

**Comment by DanielOaks** [comment]
Ah, glad you got it working! Let us know if you run into any other troubles mate.
