### ISSUE TITLE
README.md: mention that the users are also allowed to follow the latest tagged release

### ISSUE THREAD

**Issue by Mikaela** [ergochat/ergo#1803]
On our migrating network we have disagreement on how to follow Ergo releases from git.

In my opinion we should be following the latest tagged release as `git tag`s are immutable and thus we will not be surprised by new releases appearing suddenly or somehow managing to get different releases should we e.g. opt to setup a new node or decide to run a testnet. https://github.com/ergochat/ergo/releases/latest

In other vocal option Ergo tagged releases are always unstable and we need to follow the `stable` branch as the README.md says.

(In my opinion that is wrong as unlike git branches, git tags are immutable and more reliable should Ergo team not decide to do everything totally wrong (as in removing tagged releases and recreating tags pointing to something else and then requiring explicit user interaction to get local tag updated.))

**Comment by slingamn** [comment]
404bf6c2a064c7f73d298df273a0ea4090a29071
