### ISSUE TITLE
disable languages by default?

### ISSUE THREAD

**Issue by slingamn** [ergochat/ergo#1822]
Enabling languages makes Ergo slightly harder to deploy, since you have to include the languages directory. It also typically makes the CAP LS 302 response require two lines, which causes many compatibility problems, especially with older client software.

We could disable it by default and add a section to MANUAL.md explaining how to enable it?

**Comment by Mikaela** [comment]
Would it be possible to check if language support is available and if it is, enable it by default and if not, disable it?

I wonder if disabling languages by default would make Ergo more difficult to use for some users as administration could see it as just extra effort to enable them explicitly.

**Comment by pcho** [comment]
Would also advise to add some kind of limit on translations. So only those with at least help/helpop or 70% of strings translated would be added to list, and inform that translation is not yet completed.

**Comment by slingamn** [comment]
@DanielOaks any thoughts?

**Comment by slingamn** [comment]
I had a change of heart on this. It's true that the first thing that I always do, personally, when setting up an Ergo, is to turn this off. But it's an important feature of Ergo that sets us apart from most other implementations, and it's important to the community. And I would like to see client developers take more of an interest in it (it needs client support so that numeric-based l10n's don't override our translations), and disabling the feature by default sets that back.

wontfix, languages will remain enabled by default. Let's lobby client developers harder to fix their broken CAP LS parsing :-)
