### ISSUE TITLE
Document the list of oper capabilities

### ISSUE THREAD

**Issue by progval** [ergochat/ergo#1827]
There is an example list in `default.yaml`, but I can't find an exhaustive list with descriptions in the manual

**Comment by slingamn** [comment]
Thanks. The intent of the list in `default.yaml` was to be more or less self-documenting. My first impulse is to add a comment to each line, explaining what the capability does?

**Comment by progval** [comment]
Sounds good; it should also mention that it's exhaustive, so admins don't feel they need to look elsewhere
