### ISSUE TITLE
The "o" flag of WHO is ignored

### ISSUE THREAD

**Issue by progval** [ergochat/ergo#1832]
Hi,

RFCs [1459](https://datatracker.ietf.org/doc/html/rfc1459#section-4.5.1) and [2812](https://datatracker.ietf.org/doc/html/rfc2812#section-3.6.1), as well as [this WIP specification](https://github.com/ircdocs/modern-irc/pull/138) describe a "o" flag to the WHO command, used to filter out non-opers.

But Ergo ignores it:

```
1636886924.481 2 -> S: WHO * o
1636886924.481 S -> 2: :My.Little.Server 352 otherNick * ~myusernam 127.0.0.1 My.Little.Server coolNick H* :0 My UniqueReal Name
1636886924.481 S -> 2: :My.Little.Server 352 otherNick * ~username 127.0.0.1 My.Little.Server otherNick H :0 Realname
1636886924.481 S -> 2: :My.Little.Server 315 otherNick *!*@* :End of WHO list
```

(Only uses with `*` in their flags should be returned)

**Comment by slingamn** [comment]
#1730
