### ISSUE TITLE
An invite exemption is NOT a ban exemption.

### ISSUE THREAD

**Issue by yunginnanet** [ergochat/ergo#1875]
I'm sorry that I'm surely not following your contribution guidelines.
Frankly, I don't really have the time for that and this is a glaring issue.

See [PR #1874](https://github.com/ergochat/ergo/pull/1874)

**Comment by yunginnanet** [comment]
https://github.com/ergochat/ergo/pull/1874#issuecomment-997474566

**Comment by slingamn** [comment]
Discussion for this is on the PR thread (#1874). tl;dr, this can be reevaluated, but since it involves a serious compatibility break, it needs a justification and a clear use case.
