### ISSUE TITLE
INVITE command should override +b

### ISSUE THREAD

**Issue by slingamn** [ergochat/ergo#1876]
Reported by @progval in connection with #1874.

The behavior intentionally implemented in 067e62ad5ea (as per discussion recorded on #1168) was that the INVITE command should override all join restrictions, including a +b ban. However, due to a bug in 42d246b557dcb7 (#1171), INVITE is no longer recorded on a per-client basis unless the channel is invite-only. This functionally prevents INVITE from overriding +b unless the channel also happens to be +i. So this is officially a regression that was introduced in 2.4.0, and I need to write an irctest for it.

**Comment by yunginnanet** [comment]
YIKES

**Comment by slingamn** [comment]
irctest PR: https://github.com/progval/irctest/pull/125
