### ISSUE TITLE
SAQUIT Command

### ISSUE THREAD

**Issue by pcho** [ergochat/ergo#1907]
From time to time I have users that unintentionally connect few sessions (auto connect didn’t work immediately, so they connected by hand) or have little knowledge outside basics of chat usage. 

This is where `SAQUIT` could come in handy by helping disconnecting those sessions.

**Comment by Mikaela** [comment]
Is this not a `KILL`?

**Comment by slingamn** [comment]
Yeah, this sounds like either `KILL` or `NS CLIENTS LOGOUT`. The caveat is that in general those clients will respond by auto-reconnecting, which cannot be prevented without some kind of ban.
