### ISSUE TITLE
add SAVERIFY command

### ISSUE THREAD

**Issue by slingamn** [ergochat/ergo#1924]
@tacerus wanted to verify an unverified account as an administrator. Currently the only way to do this is to extract the verification code from the database.

It would probably be pretty easy to display the code as part of NS INFO.

**Comment by FiskFan1999** [comment]
Do you think it would be a good idea to paste the verification code in the +s +u server notice? Could write something like 

`-ACCOUNT- Client [usa] attempted to register account [usa] from IP xxx.xxx.xxx.xxx, pending verification, verification code XXXXXXXX`

**Comment by slingamn** [comment]
A use case for `SAVERIFY` came up here so we might do that instead: https://github.com/ircv3/ircv3-ideas/issues/89

**Comment by tacerus** [comment]
That of course seems cleaner than copying the users verification code.
