### ISSUE TITLE
LIST #idontexist results in ERR_NOSUCHCHANNEL

### ISSUE THREAD

**Issue by emersion** [ergochat/ergo#1928]
See https://github.com/ergochat/ergo/blob/6bd94391efa4d91c740f93837180e3804937b332/irc/handlers.go#L1703

`ERR_NOSUCHCHANNEL` is not part of the possible replies in https://modern.ircdocs.horse/#list-message

My client uses `LIST` to check whether a channel exists (it still offers to join the channel if it doesn't, but in that case doesn't display the topic). It bubbles up all errors to the user. It's confusing for users when get get a bunch of error messages while searching for channels.

**Comment by emersion** [comment]
Ah that was  simple fix. Thanks!

**Comment by slingamn** [comment]
All credit to you, you showed me which line to delete and then I deleted it :-p
