### ISSUE TITLE
[Documentation] can halfops invite?

### ISSUE THREAD

**Issue by Mikaela** [ergochat/ergo#1946]
MANUAL.md states:

> Halfops have some moderation privileges: they can kick users (but not ban them), change the channel topic, and grant voice privileges (see below).

in a different section:

> Anyone with persistent half-operator status or higher will also be able to join without an invite (/msg ChanServ amode #example +h alice)

However it doesn't comment on whether halfops are allowed to invite? Or are even normal users able to do that?

Runtime testnet "helpfully" says:

```
2022-W17-7 23:08:42 +0300 -- INVITE INVITE <nickname> <channel>
2022-W17-7 23:08:42 +0300 -- INVITE 
2022-W17-7 23:08:42 +0300 -- INVITE Invites the given user to the given channel, so long as you have the
2022-W17-7 23:08:42 +0300 -- INVITE appropriate channel privs.
2022-W17-7 23:08:42 +0300 -- INVITE End of /HELPOP
```

What are the appropiate channel privs? 😅

**Comment by slingamn** [comment]
1. If the channel is `+i`, only channel operators and higher can INVITE; anyone else gets `ERR_CHANOPRIVSNEEDED`
1. If the channel is `-i`, any member can INVITE, but the resulting invite will override bans only if the inviter was a channel operator or higher

Suggestions or PRs for the documentation welcome :-)

**Comment by Mikaela** [comment]
I opened a quick https://github.com/ergochat/ergo/pull/1947 which could also use suggestions, good night.
