### ISSUE TITLE
/CS AMODE multiple users at once?

### ISSUE THREAD

**Issue by xnaas** [ergochat/ergo#1963]
<sup>I don't see a previous issue for this and maybe it's been discussed and denied in IRC before, so apologies if I missed something.</sup>

---

Would it be possible to extend `/CS AMODE #channel <mode_change> <account>` to be able to do multiple accounts at once?

Use-case: I voice and hop the same users on every channel, would be much quicker to just be able to do `/CS AMODE #channel +v acct1 acct2 acct3` and `/CS AMODE #channel +h acct4` or similar.

**Comment by slingamn** [comment]
#1515, no worries
