### ISSUE TITLE
gpg signing keys?

### ISSUE THREAD

**Issue by the-rocinante** [ergochat/ergo#1968]
I see there's a checksum file to verify downloads (eg. [ergo-2.10.0-checksums.txt.sig](https://github.com/ergochat/ergo/releases/download/v2.10.0/ergo-2.10.0-checksums.txt.sig)), but I can't find the signing keys anywhere or via any public keyservers.
Can someone please clue me in?

**Comment by slingamn** [comment]
Tags and checksum files are signed with 740FC947B135E7627D4D00F21996B89DF018DCAB. This key is available here:

https://github.com/slingamn.gpg

I actually hadn't thought much about the correct way to publicize the signing key --- suggestions appreciated.

**Comment by the-rocinante** [comment]
FYI, I'm no expert on this. That said, publishing via keyserver.ubuntu.com seems to be a popular method these days since they apparently took steps to mitigate the issue of key/certificate poisoning. Apart from that, my understanding is that it's generally good practice to locate the key(s) on a separate system from the one where signed messages/data are provided. That way a compromise of one doesn't necessarily effect the other or vice versa.

**Comment by slingamn** [comment]
I uploaded the key fingerprint and the key itself to our website:

https://ergo.chat/about

I'm having some difficulties submitting the key to the Ubuntu keyserver. I tried via the command line, but the website says the key is not found. When I submitted via the website, I got:

```json
{"inserted":null,"updated":null,"ignored":["rsa4096/740fc947b135e7627d4d00f21996b89df018dcab"]}
```

**Comment by tacerus** [comment]
`gpg --keyserver hkp://keyserver.ubuntu.com --send-key <key>` ?

**Comment by tacerus** [comment]
That being said, the key is to be found here: https://keyserver.ubuntu.com/pks/lookup?search=slingamn&fingerprint=on&op=index

**Comment by slingamn** [comment]
This seems to have worked:

```
$ gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 740fc947b135e7627d4d00f21996b89df018dcab
gpg: /home/user/.gnupg/trustdb.gpg: trustdb created
gpg: key 1996B89DF018DCAB: public key "Shivaram Lingamneni <slingamn@cs.stanford.edu>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
