### ISSUE TITLE
Disable history per-client?

### ISSUE THREAD

**Issue by karx1** [ergochat/ergo#1979]
Hi, I have history enabled for the whole server, but I'd like to disable history for specific clients, namely bots such as [dircord](https://git.karx.xyz/karx/dircord). InspIRCd has a usermode `+B` which, when set, doesn't send that client any history. Is there anything like that for Ergo? I couldn't find it anywhere in the docs.

**Comment by slingamn** [comment]
It looks like `+B` is the InspIRCd [bot mode](https://docs.inspircd.org/3/modules/botmode/), correct?

I'm not sure I understand the question. By default, clients should not receive any history replay. Do you have `autoreplay-on-join` enabled in your server config? (This configuration is not recommended, but is fully supported.) If so, clients can disable it by requesting the `draft/chathistory` capability (this tells the server "I know how to request history if I want it, so don't send me any by default").

Or are you trying to prevent messages *sent* by dircord from being recorded in history? This isn't supported right now.

**Comment by FiskFan1999** [comment]
Likely not the best answer for you because it has to be set by the bot owner, but I run a bot on an ergo network and was able to avoid this by logging in to the bot's account and disabling history through, i think it was `/msg nickserv set autoreplay-lines 0` and `set autoreplay-missed off`.

**Comment by karx1** [comment]
Hi, setting autoreplay-on-join to 0 worked. Thank you!
