### ISSUE TITLE
Better way to handle accounts.email-verification.blacklist-regexes?

### ISSUE THREAD

**Issue by wkeiuluf** [ergochat/ergo#1997]
Sorry for the poor title, please adjust as needed.

---

Would be nice to be able to read a list of emails to block from a file, or something. If you want to keep something like [disposable_email_blocklist.conf](https://github.com/disposable-email-domains/disposable-email-domains/blob/master/disposable_email_blocklist.conf) in your `ergo.yaml`, you end up with literally 1000s of lines and it's a pain to keep up-to-date.

Aside: the example of regexs should actually be like: `.*@example\\.com`

**Comment by slingamn** [comment]
Good suggestion! I'll take a look at this for the next release.

**Comment by slingamn** [comment]
@progval noted that YAML includes would be ideal for this, however AIUI neither v2 nor v3 of our YAML library supports them. Switching to another library is risky in terms of compatibility breaks.
