### ISSUE TITLE
/cs amode allows adding a mode that doesn't exist

### ISSUE THREAD

**Issue by eskimo** [ergochat/ergo#2002]
I was able to `/cs amode #igloo +f eskimo` for example, which resulted in the following output:

```
[11:20:25] -ChanServ- Successfully set persistent mode +f on eskimo
[11:20:25] iglooirc.com sets mode +f eskimo
```

+f isn't anything according to https://github.com/ergochat/ergo/blob/stable/docs/MANUAL.md#channel-prefixes, however it adds to amode and will keep adding it back on rejoin.

 The problem is when doing `/cs amode #igloo -f eskimo` you'll get this output:

```
[11:20:31] -ChanServ- Account does not exist
```

So it can't be removed and doesn't do anything?

**Comment by slingamn** [comment]
Thanks, opened #2003 for this.
