### ISSUE TITLE
Request server message when always-on connects?

### ISSUE THREAD

**Issue by MystaraTheGreat** [ergochat/ergo#2040]
Is there any possibility of adding some kind of server message that gets transmitted (perhaps controllable by a user mode and/or channel mode) when an always on user connects?

**Comment by slingamn** [comment]
This should produce a CONNECT snomask as usual, if enabled (as an operator) with `MODE self +s c`, or as an auto-mode in the config:

https://github.com/ergochat/ergo/blob/abb38ce8a1afb8fc08291ef0bb4415099bf3e884/default.yaml#L680

**Comment by slingamn** [comment]
We added a separate sno category (`+d`) for always-on disconnects in #1720.

**Comment by MystaraTheGreat** [comment]
I was thinking more for regular users than for opers.
It might be nice to know when a user has become 'active'.

**Comment by slingamn** [comment]
auto-away plus https://ircv3.net/specs/extensions/away-notify.html should provide this. The default/recommended setting for auto-away is opt-in:

https://github.com/ergochat/ergo/blob/abb38ce8a1afb8fc08291ef0bb4415099bf3e884/default.yaml#L539-L540

but you can change it to `opt-out`.

**Comment by MystaraTheGreat** [comment]
Yeah, I guess that works.
Frustratingly, my client doesn't seem to have an option to actually SHOW the away messages even though it receives them.
