### ISSUE TITLE
How to configure a multi-server network? (CONNECT Unknown command)

### ISSUE THREAD

**Issue by microaaron** [ergochat/ergo#2059]
ergo doesn't seem to implement the CONNECT command([rfc1459#4.3.5](https://modern.ircdocs.horse/#connect-message)).
But I found a comment in the yaml file: "[# limits - these need to be the same across the network](https://github.com/ergochat/ergo/blob/master/default.yaml#L803)". Does this mean that multiple servers can exist in one ergo network?

**Comment by Mikaela** [comment]
https://github.com/ergochat/ergo/blob/master/docs/MANUAL.md#scalability

**Comment by microaaron** [comment]
> https://github.com/ergochat/ergo/blob/master/docs/MANUAL.md#Scalability

Thanks a lot.
