### ISSUE TITLE
ircd.db is always getting bigger and bigger

### ISSUE THREAD

**Issue by microaaron** [ergochat/ergo#2060]
Any database operation (such as /ns erase /ns passwd) will not delete obsolete data, which makes ircd.db bigger and bigger.

**Comment by slingamn** [comment]
`AutoShrinkMinSize` is also relevant; no shrinking is expected until you reach 32 MB. (My personal instance is at 30 MB after several years of operation, so it's actually never been shrunk. But I operated an instance with a different workload and I can confirm that shrinking works :-)

**Comment by microaaron** [comment]
Thanks a lot. I found the key codes.
https://github.com/ergochat/ergo/blob/378d88fee253961d3dfef76805875982f359a9a3/irc/database.go#L72-L73
https://github.com/tidwall/buntdb/blob/71088bcabfa9b2ab055f47523e7bd130d736afbf/buntdb.go#L148-L152
