### ISSUE TITLE
keep getting "Too many clients from your network" when connect using websocket protocol

### ISSUE THREAD

**Issue by kingter-sutjiadi** [ergochat/ergo#2062]
Hi tried to connect using websocket protocol, 
I've already disable throttle and disabling ip-limits count,
but i keep getting error  "Too many clients from your network"

how to avoid this from happening?

![image](https://github.com/ergochat/ergo/assets/52060866/07267ccf-7c7c-450f-8040-506ec6e949f8)

![image](https://github.com/ergochat/ergo/assets/52060866/0d0b96c5-37b2-4d3f-ac70-f7e528c21902)

**Comment by slingamn** [comment]
What version of Ergo is this? Did you [rehash](https://github.com/ergochat/ergo/blob/master/docs/MANUAL.md#rehashing) or restart the server?

**Comment by kingter-sutjiadi** [comment]
@slingamn hi thank you for the fast response, i only restart my supervisor i run the app using supervisor, the version is 2.7.0

**Comment by slingamn** [comment]
I'm not aware of a bug in this system that affects 2.7.0, but I recommend that you upgrade to 2.11.1:

https://github.com/ergochat/ergo/releases/tag/v2.11.1

unless there's something preventing you from upgrading? Your existing config should be compatible with 2.11.1.

**Comment by slingamn** [comment]
Just checking, any update on this? We have a new release as well: https://github.com/ergochat/ergo/releases/tag/v2.12.0
