### ISSUE TITLE
unmarshal errors activating logs

### ISSUE THREAD

**Issue by blackheaven** [ergochat/ergo#2085]
I am trying to enable debug logs via:

```
logging:
  level: debug
  method: stderr
  type: '* -internal -server'
```

However I get:

```
Sep 10 00:16:43 barracuda systemd[1]: Started Ergo IRC daemon.
Sep 10 00:16:44 barracuda ergo[233083]: 2023/09/10 00:16:44 Config file did not load successfully: yaml: unmarshal errors:
Sep 10 00:16:44 barracuda ergo[233083]:   line 59: cannot unmarshal !!map into []logger.LoggingConfig
Sep 10 00:16:44 barracuda systemd[1]: ergochat.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 00:16:44 barracuda systemd[1]: ergochat.service: Failed with result 'exit-code'.
```

What is the correct syntax

**Comment by slingamn** [comment]
`logging` is a list (we allow multiple logs, each with different configurations, although this feature is not commonly used in practice). Here's the correct syntax (note the `-` underneath `logging`):

```yaml
logging:
    -
        method: stderr
        type: "*"
        level: debug
```

For debugging, `*` is recommended (excluding `internal` and `server` may omit relevant context). Let me know if you have any further issues.

**Comment by blackheaven** [comment]
> `logging` is a list (we allow multiple logs, each with different configurations, although this feature is not commonly used in practice). Here's the correct syntax (note the `-` underneath `logging`):

That was the error, thanks a lot!
