### ISSUE TITLE
"read error from client : tls : first record does not look like a TLS handshake"

### ISSUE THREAD

**Issue by acagastya** [ergochat/ergo#2153]
+ Hi, I am running ergo 2.13.1, on 6697, with certificates generated from `mkcert` subcommand.
+ Logging is set to debug level.
+ When I try to connect to the server using irssi (/connect irc.example.com 6697), I am facing this error in ergo: `"read error from client : tls : first record does not look like a TLS handshake"`
+ When I try using nc `nc irc.example.com 6697` and type `USER foo * * :foo`, I get the same error.

Any suggestions how do I move forward?

**Comment by slingamn** [comment]
It sounds like this got resolved from discussion in #ergo: this is the error you get from speaking plaintext to Ergo's TLS port. We could add the Ergo-side error message ("first record does not look like") to the relevant section of the manual, so people could find it with Ctrl-F: https://github.com/ergochat/ergo/blob/master/docs/MANUAL.md#why-cant-i-connect
