### ISSUE TITLE
Error code=exited status=203/exec

### ISSUE THREAD

**Issue by zyn23** [ergochat/ergo#2155]
I made a specific user for running ergo called "ergo" :)
When i go into this user and cd into the server direcory and run "./ergo run" everything works well... but I tried to create a service so the server would start when I turn de pc on. I do systemctl enable ergo and systemctl start ergo and dont get any error messages but when I do systemctl status ergo it shows this 
`ergo.service - Ergo IRC server
     Loaded: loaded (/etc/systemd/system/ergo.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-05-22 13:47:11 WEST; 4s ago
   Duration: 2ms
    Process: 3874143 ExecStart=/home/ergo/server/start.sh (code=exited, status=203/EXEC)
   Main PID: 3874143 (code=exited, status=203/EXEC)
        CPU: 1ms`
I followed this guide [https://landchad.net/irc/](https://landchad.net/irc/) and on the end of the "Connecting to the server" section there is a ergo.service example and I just copied and paste. (Yes the server is also on the same "server" directory like in the guide)

**Comment by slingamn** [comment]
Can you check `systemctl status ergo.service` as per this answer: https://unix.stackexchange.com/a/490707 ?

**Comment by zyn23** [comment]
Same output as systemctl status ergo
![image](https://github.com/ergochat/ergo/assets/43765256/99e09c88-4d68-4aa9-a963-34dcb2a86922)
I will check the SELinux option to see if is something related

**Comment by zyn23** [comment]
It is not a SELinux related problem

**Comment by slingamn** [comment]
If you watch `journalctl --follow` while triggering the restart, do you see anything in the logs?

**Comment by zyn23** [comment]
![image](https://github.com/ergochat/ergo/assets/43765256/6502a1ca-635c-4303-b9dd-a046129ff529)
Apparently there is an error with the format i think

**Comment by slingamn** [comment]
It's probably an issue either with the shebang line in `start.sh`, or that `start.sh` is not executable: https://stackoverflow.com/a/57025791

**Comment by zyn23** [comment]
That fixed it! Thanks a lot! It was the shebang line. I wasn't specifying the shell

**Comment by slingamn** [comment]
Thanks! I should try and contact the Landchad maintainers to remove the `start.sh` recommendation, our suggested systemd unit file just points `ExecStart` directly at the `ergo` binary:

https://github.com/ergochat/ergo/blob/ca4b9c15c5c7e6009cd907e24fe31c2bf48a2083/distrib/systemd/ergo.service

**Comment by slingamn** [comment]
@termermc ^ thanks for your work on the landchad guide! Would you be able to update the guide according to the above recommendation? I think you would just have to delete the instruction to create `start.sh`, and then replace the current `ExecStart` with:

```
ExecStart=/home/ergo/server/ergo run
```

since you're already setting `WorkingDirectory`.
