### ISSUE TITLE
Enhancement: Embed default config file into the binary

### ISSUE THREAD

**Issue by al3xandros** [ergochat/ergo#2157]
I would like to suggest a feature enhancement that embeds the default configuration files
 (`default.yaml` and `traditional.yaml`) into the binary.

Rational:
- A valid configuration file suitable for the version of the binary would be always available if needed.
- The default config files can act as a quick reference for creating custom configs.

**Comment by slingamn** [comment]
Hmm, embed in what sense? Like as a string that could be output by `ergo genconfig` or similar?

**Comment by slingamn** [comment]
Oh, I see your commit now, that's nice. I'll make my own PR
