### ISSUE TITLE
“Connecting” IRC server to domain

### ISSUE THREAD

**Issue by RotatingWires** [ergochat/ergo#2178]
I’m brand new to IRC and this is the first time I try to host a server. I read the documentation and gained a general understanding of how IRC works. I was able to successfully configure the server and host it locally. What I’m stuck on is making the server accessible to people outside of my network, so my friends can join it. I have a domain and use Cloudflare. I have an Apache server running and I have another program running which are both publicly accessible using Cloudflare Tunnels. These tunnels make it really easy to make locally running servers accessible to the internet. However, when I add the ergo server to the tunnel and configure the public hostname and enter it into HexChat, the connection always fails. I get a timeout error. But if I type localhost/6667 into the HexChat server editor, it works. I tried basic port forwarding on my router just as a test which also didn’t work, and I tried making an A record in my DNS settings for my domain which didn’t work either. There’s probably something I’m missing about IRC hosting since I’m new to it, but I thought it would be the same process as connecting other apps I’ve mentioned via Cloudflare Tunnels. If anyone can help I’d appreciate it, I’ve tried looking online but for days but nothing would work. Thanks.
![image](https://github.com/user-attachments/assets/aa2a2b9f-ecd3-48fc-86e6-05bf930cf481)

**Comment by slingamn** [comment]
To the best of my knowledge, Cloudflare does not support reverse-proxying protocols other than HTTP, at least not without special software on the client side:

https://developers.cloudflare.com/cloudflare-one/applications/non-http/arbitrary-tcp/

There are a few possible workarounds:

1. You can use websockets, but then your IRC server will only be accessible to web clients. There are some instructions for Apache here: https://github.com/ergochat/ergo/blob/master/docs/MANUAL.md#kiwi-irc-and-gamja
2. You can use port forwarding from your router (if you're having trouble with this, it's likely that either your router is misconfigured, or the computer hosting Ergo has a firewall blocking access to the relevant port)
3. You can rent a VPS to run Ergo. For example, Ergo runs very well in the [OVH starter tier VPS](https://us.ovhcloud.com/vps/).

I anticipate some difficulties in discussing this asynchronously, so if you have further questions I suggest stopping by #ergo on irc.ergo.chat (you can use our [web client](https://irc.ergo.chat/kiwi/)).

**Comment by RotatingWires** [comment]
Thanks for your quick reply! I will have to consider whether I want to use websockets since, as you said, the server will only be accessible to web clients. I did allow ergo.exe through the firewall when it prompted me to, and I made sure the router’s port forwarding settings were correct but I can try that again later. I’ll follow up with how it goes in the chat you mentioned. Thanks again
