### ISSUE TITLE
Trouble with SSL Certificates

### ISSUE THREAD

**Issue by Cheecken** [ergochat/ergo#2182]
Hey! I am trying to set up an ergo instance (using the docker version) on a VPS on which I am already hosting my website. Downloading the server and configuring the MOTD and config file was easy enough and I could connect to the server using the plaintext port. Everything went great until I tried adding the SSL certificate from certbot. I had initial issues with port 80 as my website is running over nginx, so I temporarily disabled that to continue with the setup process and got my files. I tried following the guides both taking the docker documentation and general admin guide into account but no matter where I move the files around to or how often I modify the config file, I cant figure out how to make the secure connection on port 6697 work. 

I am sadly pretty much a noob at configuring things like this and I tried to troubleshoot this a lot today, I am stumped. Should I try to just make a clean install without using Docker and follow the guide again? 

For more info in case its relevant: 

The OS of the VPS is Debian 12 
I did not set up the IRC server in nginx it runs on its own
The IRC server is configured to use a subdomain to connect to it
In cloudflare the subdomain is set up to not use proxying

Any help would be greatly appreciated!

**Comment by slingamn** [comment]
How does it currently fail? (Does Ergo fail to start? Is port 6697 not exposed, so that attempts fail with "connection refused" or similar? Does Ergo accept connections on port 6697, but serve an invalid certificate?)

**Comment by Cheecken** [comment]
Port 6697 is exposed, and when sts in the config is off when I try to connect to port 6697 the client closes. When sts is enabled when I tried to sign into the server would be a loop of trying to log in, failing and then trying to login again without ever getting on. 

I commented out port 6667 in the config file and pinged the address and could reach the server.

Checking on the VPS with "docker ps" I can see ergo running

**Comment by Cheecken** [comment]
Oh yeah and before I tried connecting to the server with nginx turned off and didnt spot a difference

**Comment by slingamn** [comment]
>Port 6697 is exposed, and when sts in the config is off when I try to connect to port 6697 the client closes.

Does the TCP connection get established, or does it get refused by the server? Is there an error on the client side?

**Comment by Cheecken** [comment]
Hey! Sorry for the late reply. 

I tried connecting again both on plaintext and on port 6697. On the client side on plaintext I just connect and the console logs on the server also show that I connected. When connecting over port 6697 I don't even connect to the server at all it seems. The client side shows me this:  
![image](https://github.com/user-attachments/assets/39d2035a-7aba-474d-a276-ceeee3bfaa29)

**Comment by Cheecken** [comment]
Server side docker logs shows me this in case it helps: 
![image](https://github.com/user-attachments/assets/4e681a96-3959-426b-b801-0e9191771f1d)

**Comment by slingamn** [comment]
Is your client configured to use TLS? With debug logging enabled on the server side:

```# logging, takes inspiration from Insp
logging:
    -
        method: stderr
        type: "*"
        level: debug
```

if the client is trying to speak TLS to the plaintext port, you would see an error logline like:

```
debug : connect-ip : read error from client : tls: first record does not look like a TLS handshake
```
