### ISSUE TITLE
Get real ip from proxy

### ISSUE THREAD

**Issue by aikooo7** [ergochat/ergo#2188]
I use playit.gg as alternative for port forwarding, but then the ip in ergo is the ip of the docker container of the playit.gg client. Any way I can fix this?

**Comment by slingamn** [comment]
We support the HAProxy PROXY protocol (both versions) for regular IRC traffic, and we support the X-Forwarded-For header for websockets, but it seems unlikely that playit.gg supports either. I found a support thread about it here:

https://discuss.playit.gg/t/is-there-proxy-protocol-or-other-ip-forwarding-method-for-bungeecord/1260/4

If the playit.gg client were open-source it would probably be pretty easy to add PROXY v2 support, but it looks like it's proprietary.

**Comment by aikooo7** [comment]
> We support the HAProxy PROXY protocol (both versions) for regular IRC traffic, and we support the X-Forwarded-For header for websockets, but it seems unlikely that playit.gg supports either. I found a support thread about it here:
> 
> https://discuss.playit.gg/t/is-there-proxy-protocol-or-other-ip-forwarding-method-for-bungeecord/1260/4
> 
> If the playit.gg client were open-source it would probably be pretty easy to add PROXY v2 support, but it looks like it's proprietary.

The agent is open source: https://github.com/playit-cloud/playit-agent

Do you have any other alternative to playit.gg for this purpose?

**Comment by slingamn** [comment]
Nice, I'll take a look (it could be interesting to write some Rust).

What's your primary reason for using Playit --- hiding your home IP? Or you can't forward ports to your home IP (CGNAT, ISP restrictions)?

**Comment by aikooo7** [comment]
> Nice, I'll take a look (it could be interesting to write some Rust).
> 
> What's your primary reason for using Playit --- hiding your home IP? Or you can't forward ports to your home IP (CGNAT, ISP restrictions)?

I am using playit because I can't port forward. I use my phone as my homelab so it walks with me including in mobile data, which doesn't support port forward. I searched a lot and the unique tunnel service that supports the PROXY protocol is ngrok but only on the interprise plan.

**Comment by slingamn** [comment]
https://github.com/playit-cloud/playit-agent/issues/93 looks promising! I'm going to close this, and you can follow future developments there.

When playit.gg gets PROXY support, my recommendation would be to enable it and then use IRC-over-TLS in Ergo with this flag set to `true`:

https://github.com/ergochat/ergo/blob/796bc198edc809764da18056ea9eefbfa43fefa2/default.yaml#L57-L60

The certificate won't be verifiable but you can potentially instruct users to pin it.

**Comment by aikooo7** [comment]
I can confirm this is implemented at playit.gg side and working
