### ISSUE TITLE
[Question] How to restrict users from using a certain command?

### ISSUE THREAD

**Issue by rainbowsource** [ergochat/ergo#2192]
For example, I want to restrict or prohibit users from using the "/ns unregister" command, what should I do?

**Comment by slingamn** [comment]
Could you say more about why you want to do this?

**Comment by rainbowsource** [comment]
Haha, I want to prohibit users from canceling their accounts. It's just theoretical.

**Comment by rainbowsource** [comment]
I found a good, safe and convenient way: I just comment out the unnecessary functions in the code. Thanks for your response.

**Comment by slingamn** [comment]
If you're willing to patch Ergo, that will work. You can also add an operator privilege to the nickserv command definition, as here:

https://github.com/ergochat/ergo/blob/f68d32b4eea702934d96377144be4f975d3fefc7/irc/nickserv.go#L124

This technique will also work for regular IRC commands:

https://github.com/ergochat/ergo/blob/f68d32b4eea702934d96377144be4f975d3fefc7/irc/commands.go#L113

**Comment by slingamn** [comment]
That said, I'm not sure what this really accomplishes. If the goal is to prevent the reuse of registered account names, `NS UNREGISTER` already does this: a name that was registered and subsequently unregistered cannot be registered again. (`NS ERASE` exists as an escape hatch for operators to allow re-registration in this case.) If the goal is to force the account to remain active and in the system, the user can disable [always-on](https://github.com/ergochat/ergo/blob/master/docs/USERGUIDE.md#always-on) (if enabled), `/part` from all channels, and then disconnect, which is functionally similar to the account being unregistered.

**Comment by rainbowsource** [comment]
@slingamn Thank you very much.
