### ISSUE TITLE
Possible channel +b issue

### ISSUE THREAD

**Issue by DanielOaks** [ergochat/ergo#315]
> when you do `"mode #chan +b *"` will result `"nickname sets mode +b *"` just like that, not `*!*@*` and when you do `/invite X`, X cannot join
>
> **<dan->** hmm, the first part of that (not `*!*@*`) sounds like a bug. `/invite X` will not let X join if they are banned right now... I might add a note or look at other servers to see what they do for that

Some stuff for me to look into. tl;dr make sure if someone sets `/mode +b gus`, the server properly and correctly changes it to `gus!*@*` and sets that, maybe, if other servers do that same thing. With inviting a banned user, either force-let-them-join or notify the user doing the inviting that the person's banned and cannot be invited, match existing ircd behaviour if one's done by all other servers.

**Comment by slingamn** [comment]
The invite issue is likely the same as #313 and the behavior in master is likely as described in #314 (i.e., invites override bans).

**Comment by DanielOaks** [comment]
Hmm, yeah could be for sure. On the side these at least raise the questions of how to handle some specific cases we likely haven't handled yet, so we can leave this issue up for us to dig into those.

**Comment by slingamn** [comment]
Closing this for now
